name: CI

on:
    push:
        branches: [master]
        paths:
            - "**/*.ts"
            - "package.json"
            - "package-lock.json"
            - "tsconfig.json"
            - ".github/workflows/**"
    pull_request:
        branches: ["**"]
        paths:
            - "**/*.ts"
            - "package.json"
            - "package-lock.json"
            - "tsconfig.json"
            - ".github/workflows/**"

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

env:
    NODE_OPTIONS: --enable-source-maps
    CI: true

jobs:
    typecheck:
        name: TypeCheck (tsc)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: Install deps
              run: npm ci

            - name: TypeCheck
              run: npm run typecheck

    build:
        name: Build (tsc emit)
        runs-on: ubuntu-latest
        needs: typecheck
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: Install deps
              run: npm ci

            - name: Clean
              run: npm run clean || true

            - name: Build
              run: npm run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/**
                  if-no-files-found: error
                  retention-days: 7

    test:
        name: Test & Coverage (Node ${{ matrix.node }})
        runs-on: ubuntu-latest
        needs: typecheck
        strategy:
            fail-fast: false
            matrix:
                node: [18, 20, 22]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
                  cache: npm

            - name: Install deps
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run tests
              run: npm test

            - name: Coverage
              run: npm run coverage

            - name: Upload coverage
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-node-${{ matrix.node }}
                  path: coverage/**
                  if-no-files-found: warn
                  retention-days: 7

    smoke:
        name: Smoke Run
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: Install deps (prod only)
              run: npm ci --omit=dev

            - name: Restore build
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist

            - name: Start once to ensure no runtime crash
              run: node --enable-source-maps dist/index.js || true

    summary:
        name: CI Summary
        runs-on: ubuntu-latest
        needs: [typecheck, build, test, smoke]
        steps:
            - name: Status
              run: |
                  echo "Typecheck: ${{ needs.typecheck.result }}"
                  echo "Build:     ${{ needs.build.result }}"
                  echo "Test:      ${{ needs.test.result }}"
                  echo "Smoke:     ${{ needs.smoke.result }}"
